/*
 * Decompiled with CFR 0.152.
 */
package noppes.npcs;

import cpw.mods.fml.client.registry.ClientRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import gloomyfolken.bundle.common.core.InvokeSideOnly;
import gloomyfolken.mods.core.main.GloomyCore;
import net.minecraft.block.Block;
import net.minecraft.item.EnumArmorMaterial;
import net.minecraft.item.Item;
import noppes.npcs.CreativeTabNpcs;
import noppes.npcs.CustomNpcs;
import noppes.npcs.blocks.BlockBlood;
import noppes.npcs.blocks.BlockCarpentryBench;
import noppes.npcs.blocks.BlockMailbox;
import noppes.npcs.blocks.BlockNpcRedstone;
import noppes.npcs.blocks.BlockNpcSpawner;
import noppes.npcs.blocks.BlockWaypoint;
import noppes.npcs.blocks.TileBlockAnvil;
import noppes.npcs.blocks.TileMailbox;
import noppes.npcs.blocks.TileNpcSpawner;
import noppes.npcs.blocks.TileRedstoneBlock;
import noppes.npcs.blocks.TileWaypoint;
import noppes.npcs.items.EnumNpcToolMaterial;
import noppes.npcs.items.ItemBanjo;
import noppes.npcs.items.ItemBattleAxe;
import noppes.npcs.items.ItemBullet;
import noppes.npcs.items.ItemClaw;
import noppes.npcs.items.ItemCrossbow;
import noppes.npcs.items.ItemDagger;
import noppes.npcs.items.ItemDaggerReversed;
import noppes.npcs.items.ItemElementalStaff;
import noppes.npcs.items.ItemExcalibur;
import noppes.npcs.items.ItemGlaive;
import noppes.npcs.items.ItemGun;
import noppes.npcs.items.ItemGunChainsaw;
import noppes.npcs.items.ItemKunai;
import noppes.npcs.items.ItemKunaiReversed;
import noppes.npcs.items.ItemMachineGun;
import noppes.npcs.items.ItemMusket;
import noppes.npcs.items.ItemNpcApprover;
import noppes.npcs.items.ItemNpcCloner;
import noppes.npcs.items.ItemNpcDuplicator;
import noppes.npcs.items.ItemNpcInterface;
import noppes.npcs.items.ItemNpcMovingPath;
import noppes.npcs.items.ItemNpcWand;
import noppes.npcs.items.ItemNpcWeaponInterface;
import noppes.npcs.items.ItemOrb;
import noppes.npcs.items.ItemRotatedShield;
import noppes.npcs.items.ItemScythe;
import noppes.npcs.items.ItemShield;
import noppes.npcs.items.ItemSlingshot;
import noppes.npcs.items.ItemSpear;
import noppes.npcs.items.ItemSquadController;
import noppes.npcs.items.ItemStaff;
import noppes.npcs.items.ItemThrowingShuriken;
import noppes.npcs.items.ItemThrowingWeapon;
import noppes.npcs.items.ItemViolin;
import noppes.npcs.items.ItemWand;
import noppes.npcs.items.NpcArmor;

public class CustomItems {
    public static Item wand;
    public static Item cloner;
    public static Item duplicator;
    public static Item approver;
    public static ItemSquadController squadController;
    public static Item moving;
    public static Item banjo;
    public static Item violin;
    public static Item violinbow;
    public static Item harp;
    public static Item guitar;
    public static Item coinWood;
    public static Item coinStone;
    public static Item coinIron;
    public static Item coinGold;
    public static Item coinDiamond;
    public static Item coinBronze;
    public static Item coinEmerald;
    public static Item moneyBag;
    public static Item bulletWood;
    public static Item bulletStone;
    public static Item bulletIron;
    public static Item bulletGold;
    public static Item bulletDiamond;
    public static Item bulletBronze;
    public static Item bulletEmerald;
    public static Item bulletBlack;
    public static Item gunWood;
    public static Item gunStone;
    public static Item gunIron;
    public static Item gunGold;
    public static Item gunDiamond;
    public static Item gunBronze;
    public static Item gunEmerald;
    public static Item gunMachine;
    public static Item tridentWood;
    public static Item tridentStone;
    public static Item tridentIron;
    public static Item tridentGold;
    public static Item tridentDiamond;
    public static Item tridentBronze;
    public static Item tridentEmerald;
    public static Item tridentCurse;
    public static Item spellNature;
    public static Item spellArcane;
    public static Item spellItem;
    public static Item spellLightning;
    public static Item spellIce;
    public static Item spellFire;
    public static Item spellDark;
    public static Item spellHoly;
    public static Item staffWood;
    public static Item staffStone;
    public static Item staffIron;
    public static Item staffGold;
    public static Item staffDiamond;
    public static Item staffBronze;
    public static Item staffEmerald;
    public static Item staffElemental;
    public static Item orb;
    public static Item mana;
    public static Item kunai;
    public static Item shuriken;
    public static Item excalibur;
    public static Item letter;
    public static Block innDoor;
    public static Block redstoneBlock;
    public static Block carpentyBench;
    public static Block mailbox;
    public static Block waypoint;
    public static Item crossbowBolt;
    public static CreativeTabNpcs tab;
    public static CreativeTabNpcs tabArmor;
    public static CreativeTabNpcs tabWeapon;
    public static CreativeTabNpcs tabMisc;
    private static Block npcSpawnerBlock;

    public static void load() {
        GameRegistry.registerTileEntity(TileRedstoneBlock.class, "TileRedstoneBlock");
        GameRegistry.registerTileEntity(TileBlockAnvil.class, "TileBlockAnvil");
        GameRegistry.registerTileEntity(TileMailbox.class, "TileMailbox");
        GameRegistry.registerTileEntity(TileWaypoint.class, "TileWaypoint");
        wand = new ItemNpcWand(26724).setUnlocalizedName("npcWand").setFull3D();
        cloner = new ItemNpcCloner(26725).setUnlocalizedName("npcMobCloner").setFull3D();
        duplicator = new ItemNpcDuplicator(26726).setUnlocalizedName("npcMobDuplicator").setFull3D();
        approver = new ItemNpcApprover(26944).setUnlocalizedName("npcMobApprover").setFull3D();
        squadController = (ItemSquadController)new ItemSquadController(26945).setUnlocalizedName("squadController").setFull3D();
        moving = new ItemNpcMovingPath(26716).setUnlocalizedName("npcMovingPath").setFull3D();
        redstoneBlock = new BlockNpcRedstone(CustomNpcs.BlockStartId).setBlockUnbreakable().setResistance(2000.0f).setUnlocalizedName("npcRedstoneBlock").setTextureName("customnpcs:npcRedstoneBlock");
        GameRegistry.registerBlock(redstoneBlock, "npcRedstoneBlock");
        carpentyBench = new BlockCarpentryBench(CustomNpcs.BlockStartId + 1).setUnlocalizedName("npcCarpentyBench").setHardness(5.0f).setResistance(10.0f).setStepSound(Block.soundWoodFootstep).setTextureName("customnpcs:npcCarpentryBench");
        GameRegistry.registerBlock(carpentyBench, "npcCarpentyBench");
        CustomItems.tab.icon = CustomItems.carpentyBench.blockID;
        mailbox = new BlockMailbox(CustomNpcs.BlockStartId + 3).setUnlocalizedName("npcMailbox").setHardness(5.0f).setResistance(10.0f).setStepSound(Block.soundMetalFootstep);
        GameRegistry.registerBlock(mailbox, "npcMailbox");
        waypoint = new BlockWaypoint(CustomNpcs.BlockStartId + 4).setUnlocalizedName("npcWaypoint").setHardness(5.0f).setResistance(10.0f).setStepSound(Block.soundMetalFootstep).setTextureName("customnpcs:npcWaypoint");
        GameRegistry.registerBlock(waypoint, "npcWaypoint");
        npcSpawnerBlock = new BlockNpcSpawner(CustomNpcs.BlockStartId + 5);
        GameRegistry.registerBlock(npcSpawnerBlock, "npc_spawner");
        GameRegistry.registerTileEntity(TileNpcSpawner.class, "tileNpcSpawner");
        InvokeSideOnly.client(GloomyCore.side.isClient(), () -> ClientRegistry.bindTileEntitySpecialRenderer(TileNpcSpawner.class, new zfvd()));
        if (!CustomNpcs.DisableExtraNpcItems) {
            tabArmor = new CreativeTabNpcs("cnpcsa");
            tabWeapon = new CreativeTabNpcs("cnpcsw");
            tabMisc = new CreativeTabNpcs("cnpcsm");
            banjo = new ItemBanjo(26732).setUnlocalizedName("npcBanjo").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBanjo");
            violin = new ItemViolin(26733).setUnlocalizedName("npcViolin").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcViolin");
            violinbow = new ItemNpcInterface(26734).setUnlocalizedName("npcViolinBow").setFull3D().setMaxStackSize(1).setCreativeTab(tabMisc).setTextureName("customnpcs:npcViolinBow");
            harp = new ItemViolin(26735).setUnlocalizedName("npcHarp").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcHarp");
            guitar = new ItemBanjo(26731).setUnlocalizedName("npcGuitar").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcGuitar");
            Block block = new BlockBlood(CustomNpcs.BlockStartId + 2).setUnlocalizedName("npcBloodBlock").setTextureName("customnpcs:npcBloodBlock");
            GameRegistry.registerBlock(block, "npcBloodBlock");
            coinWood = new ItemNpcInterface(26717).setUnlocalizedName("npcCoinWooden").setCreativeTab(tabMisc).setTextureName("customnpcs:npcCoinWooden");
            coinStone = new ItemNpcInterface(26718).setUnlocalizedName("npcCoinStone").setCreativeTab(tabMisc).setTextureName("customnpcs:npcCoinStone");
            coinBronze = new ItemNpcInterface(26719).setUnlocalizedName("npcCoinBronze").setCreativeTab(tabMisc).setTextureName("customnpcs:npcCoinBronze");
            coinIron = new ItemNpcInterface(26720).setUnlocalizedName("npcCoinIron").setCreativeTab(tabMisc).setTextureName("customnpcs:npcCoinIron");
            coinGold = new ItemNpcInterface(26721).setUnlocalizedName("npcCoinGold").setCreativeTab(tabMisc).setTextureName("customnpcs:npcCoinGold");
            coinDiamond = new ItemNpcInterface(26722).setUnlocalizedName("npcCoinDiamond").setCreativeTab(tabMisc).setTextureName("customnpcs:npcCoinDiamond");
            coinEmerald = new ItemNpcInterface(26723).setUnlocalizedName("npcCoinEmerald").setCreativeTab(tabMisc).setTextureName("customnpcs:npcCoinEmerald");
            gunWood = new ItemGun(26820, EnumNpcToolMaterial.WOOD).setUnlocalizedName("npcWoodenGun").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcWoodenGun");
            bulletWood = new ItemBullet(26821, EnumNpcToolMaterial.WOOD).setUnlocalizedName("npcWoodenBullet").setMaxStackSize(64).setTextureName("customnpcs:npcWoodenBullet");
            gunStone = new ItemGun(26822, EnumNpcToolMaterial.STONE).setUnlocalizedName("npcStoneGun").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcStoneGun");
            bulletStone = new ItemBullet(26823, EnumNpcToolMaterial.STONE).setUnlocalizedName("npcStoneBullet").setMaxStackSize(64).setTextureName("customnpcs:npcStoneBullet");
            gunIron = new ItemGun(26824, EnumNpcToolMaterial.IRON).setUnlocalizedName("npcIronGun").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcIronGun");
            bulletIron = new ItemBullet(26825, EnumNpcToolMaterial.IRON).setUnlocalizedName("npcIronBullet").setMaxStackSize(64).setTextureName("customnpcs:npcIronBullet");
            gunGold = new ItemGun(26826, EnumNpcToolMaterial.GOLD).setUnlocalizedName("npcGoldGun").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcGoldGun");
            bulletGold = new ItemBullet(26827, EnumNpcToolMaterial.GOLD).setUnlocalizedName("npcGoldenBullet").setMaxStackSize(64).setTextureName("customnpcs:npcGoldenBullet");
            gunDiamond = new ItemGun(26828, EnumNpcToolMaterial.DIA).setUnlocalizedName("npcDiamondGun").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcDiamondGun");
            bulletDiamond = new ItemBullet(26829, EnumNpcToolMaterial.DIA).setUnlocalizedName("npcDiamondBullet").setMaxStackSize(64).setTextureName("customnpcs:npcDiamondBullet");
            gunBronze = new ItemGun(26830, EnumNpcToolMaterial.BRONZE).setUnlocalizedName("npcBronzeGun").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBronzeGun");
            bulletBronze = new ItemBullet(26831, EnumNpcToolMaterial.BRONZE).setUnlocalizedName("npcBronzeBullet").setMaxStackSize(64).setTextureName("customnpcs:npcBronzeBullet");
            gunEmerald = new ItemGun(26832, EnumNpcToolMaterial.EMERALD).setUnlocalizedName("npcEmeraldGun").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcEmeraldGun");
            bulletEmerald = new ItemBullet(26833, EnumNpcToolMaterial.EMERALD).setUnlocalizedName("npcEmeraldBullet").setMaxStackSize(64).setTextureName("customnpcs:npcEmeraldBullet");
            gunMachine = new ItemMachineGun(26834).setUnlocalizedName("npcMachineGun").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcMachineGun");
            bulletBlack = new ItemBullet(26835, EnumNpcToolMaterial.WOOD).setUnlocalizedName("npcBlackBullet").setMaxStackSize(64).setTextureName("customnpcs:npcBlackBullet");
            txfz txfz2 = txfz._d;
            txfz txfz3 = txfz._d;
            tridentWood = new ItemSpear(26840, txfz._a).setUnlocalizedName("npcWoodenTrident").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcWoodenTrident");
            tridentStone = new ItemSpear(26841, txfz._b).setUnlocalizedName("npcStoneTrident").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcStoneTrident");
            tridentIron = new ItemSpear(26842, txfz._c).setUnlocalizedName("npcIronTrident").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcIronTrident");
            tridentGold = new ItemSpear(26843, txfz._e).setUnlocalizedName("npcGoldTrident").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcGoldTrident");
            tridentDiamond = new ItemSpear(26844, txfz._d).setUnlocalizedName("npcDiamondTrident").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcDiamondTrident");
            tridentBronze = new ItemSpear(26845, txfz2).setUnlocalizedName("npcBronzeTrident").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBronzeTrident");
            tridentEmerald = new ItemSpear(26846, txfz3).setUnlocalizedName("npcEmeraldTrident").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcEmeraldTrident");
            tridentCurse = new ItemSpear(26847, txfz3).setUnlocalizedName("npcCursedTrident").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcCursedTrident");
            spellNature = new ItemNpcInterface(26930).setUnlocalizedName("npcNatureSpell").setCreativeTab(tabMisc).setTextureName("customnpcs:npcNatureSpell");
            spellArcane = new ItemNpcInterface(26931).setUnlocalizedName("npcArcaneSpell").setCreativeTab(tabMisc).setTextureName("customnpcs:npcArcaneSpell");
            spellLightning = new ItemNpcInterface(26932).setUnlocalizedName("npcLightningSpell").setCreativeTab(tabMisc).setTextureName("customnpcs:npcLightningSpell");
            spellIce = new ItemNpcInterface(26933).setUnlocalizedName("npcIceSpell").setCreativeTab(tabMisc).setTextureName("customnpcs:npcIceSpell");
            spellFire = new ItemNpcInterface(26934).setUnlocalizedName("npcFireSpell").setCreativeTab(tabMisc).setTextureName("customnpcs:npcFireSpell");
            spellDark = new ItemNpcInterface(26935).setUnlocalizedName("npcDarkSpell").setCreativeTab(tabMisc).setTextureName("customnpcs:npcDarkSpell");
            spellHoly = new ItemNpcInterface(26936).setUnlocalizedName("npcHolySpell").setCreativeTab(tabMisc).setTextureName("customnpcs:npcHolySpell");
            orb = new ItemOrb(26937).setUnlocalizedName("npcOrb").setCreativeTab(tabMisc).setTextureName("customnpcs:npcOrb");
            mana = new ItemNpcInterface(26938).setUnlocalizedName("npcMana").setCreativeTab(tabWeapon).setTextureName("customnpcs:npcMana");
            Item item = new ItemOrb(26939).setUnlocalizedName("npcBrokenOrb").setCreativeTab(tabMisc).setTextureName("customnpcs:npcBrokenOrb");
            kunai = new ItemKunai(26910, txfz._c).setUnlocalizedName("npcKunai").setMaxStackSize(1).setFull3D().setTextureName("customnpcs:npcKunai");
            Item item2 = new ItemKunaiReversed(26911, txfz._c).setUnlocalizedName("npcReverseKunai").setMaxStackSize(1).setFull3D().setTextureName("customnpcs:npcReverseKunai");
            item2 = new ItemThrowingShuriken(26912).setRotating().setDropItem().setUnlocalizedName("npcShuriken").setFull3D().setTextureName("customnpcs:npcShuriken");
            shuriken = new ItemThrowingWeapon(26913).setDamage(4).setRotating().setDropItem().setUnlocalizedName("npcGiantShuriken").setFull3D().setTextureName("customnpcs:npcGiantShuriken");
            Item item3 = new ItemNpcWeaponInterface(26914, txfz._c).setUnlocalizedName("npcKatana").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcKatana");
            Item item4 = new ItemDagger(26915, txfz._c).setUnlocalizedName("npcKukri").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcKukri");
            Item item5 = new ItemSpear(26800, txfz._c).setUnlocalizedName("npcGolfClub").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcGolfClub");
            Item item6 = new ItemWand(26801).setUnlocalizedName("npcMagicWand").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcMagicWand");
            Item item7 = new ItemNpcInterface(26802).setUnlocalizedName("npcChickenSword").setFull3D().setMaxStackSize(1).setCreativeTab(tabMisc).setTextureName("customnpcs:npcChickenSword");
            Item item8 = new ItemNpcInterface(26803).setUnlocalizedName("npcHandCuffs").setFull3D().setMaxStackSize(1).setCreativeTab(tabMisc).setTextureName("customnpcs:npcHandCuffs");
            Item item9 = new ItemNpcWeaponInterface(26804, txfz._b).setUnlocalizedName("npcHammer").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcHammer");
            Item item10 = new ItemNpcWeaponInterface(26805, txfz._c).setUnlocalizedName("npcBaseballBat").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBaseballBat");
            Item item11 = new ItemNpcWeaponInterface(26806, txfz._c).setUnlocalizedName("npcLeadPipe").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcLeadPipe");
            Item item12 = new ItemNpcWeaponInterface(26807, txfz._c).setUnlocalizedName("npcCleaver").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcCleaver");
            Item item13 = new ItemNpcWeaponInterface(26808, txfz._c).setUnlocalizedName("npcSaber").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcSaber");
            Item item14 = new ItemSpear(26809, txfz._c).setUnlocalizedName("npcHockeyStick").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcHockeyStick");
            item9 = new ItemSpear(26810, txfz._c).setUnlocalizedName("npcSledgeHammer").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcSledgeHammer");
            Item item15 = new ItemNpcWeaponInterface(26811, txfz._c).setUnlocalizedName("npcBrokenBottle").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBrokenBottle");
            item4 = new ItemDagger(26812, txfz._b).setUnlocalizedName("npcCombatKnive").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcCombatKnive");
            Item item16 = new nvwz(26813).setUnlocalizedName("npcLighter").setMaxStackSize(1).setCreativeTab(tabMisc).setTextureName("customnpcs:npcLighter");
            Item item17 = new ItemNpcWeaponInterface(26714, txfz._c).setUnlocalizedName("npcMacuahuitl").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcMacuahuitl");
            Item item18 = new ItemGlaive(26715, txfz._c).setUnlocalizedName("npcBoStaff").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBoStaff");
            Item item19 = new ItemDagger(26757, txfz._c).setUnlocalizedName("npcSaiBlade").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcSaiBlade");
            Item item20 = new ItemSlingshot(26767).setUnlocalizedName("npcSlingshot").setFull3D().setTextureName("customnpcs:npcSlingshot");
            Item item21 = new ItemMusket(26758).setUnlocalizedName("npcMusket").setFull3D().setTextureName("customnpcs:npcMusket");
            Item item22 = new ItemCrossbow(26768).setUnlocalizedName("npcCrossbow").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcCrossbow");
            crossbowBolt = new ItemBullet(26769, EnumNpcToolMaterial.WOOD).setUnlocalizedName("npcCrossBolt").setMaxStackSize(64).setTextureName("customnpcs:npcCrossBolt");
            Item item23 = new ItemNpcWeaponInterface(26814, txfz._b).setUnlocalizedName("npcBatton").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBatton");
            Item item24 = new ItemGunChainsaw(26815, txfz._d).setUnlocalizedName("npcGunChainsaw").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcGunChainsaw");
            Item item25 = new ItemNpcWeaponInterface(26816, txfz._c).setUnlocalizedName("npcRapier").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcRapier");
            Item item26 = new ItemNpcWeaponInterface(26817, txfz._c).setUnlocalizedName("npcCrowbar").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcCrowbar");
            Item item27 = new ItemNpcWeaponInterface(26818, txfz._c).setUnlocalizedName("npcPipeWrench").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcPipeWrench");
            Item item28 = new ItemDagger(26819, txfz._c).setUnlocalizedName("npcSwissArmyKnife").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcSwissArmyKnife");
            Item item29 = new ItemNpcWeaponInterface(26836, txfz._c).setUnlocalizedName("npcWrench").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcWrench");
            excalibur = new ItemExcalibur(26799, txfz._d).setUnlocalizedName("npcExcalibur").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcExcalibur");
            Item item30 = new ItemShield(26729, EnumNpcToolMaterial.WOOD).setUnlocalizedName("npcWoodenShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcWoodenShield");
            item30 = new ItemShield(26730, EnumNpcToolMaterial.STONE).setUnlocalizedName("npcStoneShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcStoneShield");
            item30 = new ItemShield(26736, EnumNpcToolMaterial.IRON).setUnlocalizedName("npcIronShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcIronShield");
            item30 = new ItemShield(26737, EnumNpcToolMaterial.GOLD).setUnlocalizedName("npcGoldenShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcGoldenShield");
            item30 = new ItemShield(26738, EnumNpcToolMaterial.DIA).setUnlocalizedName("npcDiaShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcDiaShield");
            item30 = new ItemShield(26739, EnumNpcToolMaterial.BRONZE).setUnlocalizedName("npcBronzeShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBronzeShield");
            item30 = new ItemRotatedShield(26740, EnumNpcToolMaterial.WOOD).setUnlocalizedName("npcFullWoodenShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcFullWoodenShield");
            item30 = new ItemRotatedShield(26741, EnumNpcToolMaterial.STONE).setUnlocalizedName("npcFullStoneShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcFullStoneShield");
            item30 = new ItemRotatedShield(26742, EnumNpcToolMaterial.IRON).setUnlocalizedName("npcFullIronShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcFullIronShield");
            item30 = new ItemRotatedShield(26743, EnumNpcToolMaterial.GOLD).setUnlocalizedName("npcFullGoldenShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcFullGoldenShield");
            item30 = new ItemRotatedShield(26744, EnumNpcToolMaterial.DIA).setUnlocalizedName("npcFullDiaShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcFullDiaShield");
            item30 = new ItemRotatedShield(26745, EnumNpcToolMaterial.BRONZE).setUnlocalizedName("npcFullBronzeShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcFullBronzeShield");
            item30 = new ItemRotatedShield(26727, EnumNpcToolMaterial.EMERALD).setUnlocalizedName("npcFullEmeraldShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcFullEmeraldShield");
            item30 = new ItemShield(26728, EnumNpcToolMaterial.EMERALD).setUnlocalizedName("npcEmeraldShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcEmeraldShield");
            item30 = new ItemShield(26746, EnumNpcToolMaterial.IRON).setUnlocalizedName("npcHeaterShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcHeaterShield");
            item30 = new ItemShield(26747, EnumNpcToolMaterial.IRON).setUnlocalizedName("npcCryscentShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcCryscentShield");
            item30 = new ItemShield(26748, EnumNpcToolMaterial.IRON).setUnlocalizedName("npcScutumShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcScutumShield");
            item30 = new ItemRotatedShield(26749, EnumNpcToolMaterial.IRON).setUnlocalizedName("npcTowerShield").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcTowerShield");
            Item item31 = new ItemSpear(26750, txfz._a).setUnlocalizedName("npcWoodenSpear").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcWoodenSpear");
            item31 = new ItemSpear(26751, txfz._b).setUnlocalizedName("npcStoneSpear").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcStoneSpear");
            item31 = new ItemSpear(26752, txfz._c).setUnlocalizedName("npcIronSpear").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcIronSpear");
            item31 = new ItemSpear(26753, txfz._e).setUnlocalizedName("npcGoldenSpear").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcGoldenSpear");
            item31 = new ItemSpear(26754, txfz._d).setUnlocalizedName("npcDiamondSpear").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcDiamondSpear");
            item31 = new ItemSpear(26755, txfz2).setUnlocalizedName("npcBronzeSpear").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBronzeSpear");
            item31 = new ItemSpear(26756, txfz3).setUnlocalizedName("npcEmeraldSpear").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcEmeraldSpear");
            Item item32 = new ItemBattleAxe(26760, txfz._a).setUnlocalizedName("npcWoodenBattleAxe").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcWoodenBattleAxe");
            item32 = new ItemBattleAxe(26761, txfz._b).setUnlocalizedName("npcStoneBattleAxe").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcStoneBattleAxe");
            item32 = new ItemBattleAxe(26762, txfz._c).setUnlocalizedName("npcIronBattleAxe").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcIronBattleAxe");
            item32 = new ItemBattleAxe(26763, txfz._e).setUnlocalizedName("npcGoldenBattleAxe").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcGoldenBattleAxe");
            item32 = new ItemBattleAxe(26764, txfz._d).setUnlocalizedName("npcDiamondBattleAxe").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcDiamondBattleAxe");
            item32 = new ItemBattleAxe(26765, txfz2).setUnlocalizedName("npcBronzeBattleAxe").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBronzeBattleAxe");
            item32 = new ItemBattleAxe(26766, txfz3).setUnlocalizedName("npcEmeraldBattleAxe").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcEmeraldBattleAxe");
            Item item33 = new ItemNpcWeaponInterface(26770, txfz._a).setUnlocalizedName("npcWoodenMace").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcWoodenMace");
            item33 = new ItemNpcWeaponInterface(26771, txfz._b).setUnlocalizedName("npcStoneMace").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcStoneMace");
            item33 = new ItemNpcWeaponInterface(26772, txfz._c).setUnlocalizedName("npcIronMace").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcIronMace");
            item33 = new ItemNpcWeaponInterface(26773, txfz._e).setUnlocalizedName("npcGoldenMace").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcGoldenMace");
            item33 = new ItemNpcWeaponInterface(26774, txfz._d).setUnlocalizedName("npcDiamondMace").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcDiamondMace");
            item33 = new ItemNpcWeaponInterface(26775, txfz2).setUnlocalizedName("npcBronzeMace").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBronzeMace");
            item33 = new ItemNpcWeaponInterface(26776, txfz3).setUnlocalizedName("npcEmeraldMace").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcEmeraldMace");
            Item item34 = new ItemDagger(26700, txfz._a).setUnlocalizedName("npcWoodenDagger").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcWoodenDagger");
            item34 = new ItemDaggerReversed(26701, (ItemDagger)item34, txfz._a).setUnlocalizedName("npcWoodenReversedDagger").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcWoodenDagger");
            item34 = new ItemDagger(26702, txfz._b).setUnlocalizedName("npcStoneDagger").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcStoneDagger");
            item34 = new ItemDaggerReversed(26703, (ItemDagger)item34, txfz._b).setUnlocalizedName("npcStoneReversedDagger").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcStoneDagger");
            item34 = new ItemDagger(26704, txfz._c).setUnlocalizedName("npcIronDagger").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcIronDagger");
            item34 = new ItemDaggerReversed(26705, (ItemDagger)item34, txfz._c).setUnlocalizedName("npcIronReversedDagger").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcIronDagger");
            item34 = new ItemDagger(26706, txfz._e).setUnlocalizedName("npcGoldenDagger").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcGoldenDagger");
            item34 = new ItemDaggerReversed(26707, (ItemDagger)item34, txfz._e).setUnlocalizedName("npcGoldenReversedDagger").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcGoldenDagger");
            item34 = new ItemDagger(26708, txfz._d).setUnlocalizedName("npcDiamondDagger").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcDiamondDagger");
            item34 = new ItemDaggerReversed(26709, (ItemDagger)item34, txfz._d).setUnlocalizedName("npcDiamondReversedDagger").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcDiamondDagger");
            item34 = new ItemDagger(26710, txfz2).setUnlocalizedName("npcBronzeDagger").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBronzeDagger");
            item34 = new ItemDaggerReversed(26711, (ItemDagger)item34, txfz2).setUnlocalizedName("npcBronzeReversedDagger").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBronzeDagger");
            item34 = new ItemDagger(26712, txfz3).setUnlocalizedName("npcEmeraldDagger").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcEmeraldDagger");
            item34 = new ItemDaggerReversed(26713, (ItemDagger)item34, txfz3).setUnlocalizedName("npcEmeraldReversedDagger").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcEmeraldDagger");
            Item item35 = new ItemClaw(26850, txfz._c).setUnlocalizedName("npcNinjaClaw").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcNinjaClaw");
            item35 = new ItemClaw(26851, txfz._c).setUnlocalizedName("npcSteelClaw").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcSteelClaw");
            item35 = new ItemClaw(26852, txfz._c).setUnlocalizedName("npcBearClaw").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBearClaw");
            item35 = new ItemClaw(26853, txfz._c).setUnlocalizedName("npcKatar").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcKatar");
            staffWood = new ItemStaff(26777, EnumNpcToolMaterial.WOOD).setUnlocalizedName("npcWoodenStaff").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcWoodenStaff");
            staffStone = new ItemStaff(26778, EnumNpcToolMaterial.STONE).setUnlocalizedName("npcStoneStaff").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcStoneStaff");
            staffIron = new ItemStaff(26779, EnumNpcToolMaterial.IRON).setUnlocalizedName("npcIronStaff").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcIronStaff");
            staffGold = new ItemStaff(26780, EnumNpcToolMaterial.GOLD).setUnlocalizedName("npcGoldenStaff").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcGoldenStaff");
            staffDiamond = new ItemStaff(26781, EnumNpcToolMaterial.DIA).setUnlocalizedName("npcDiamondStaff").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcDiamondStaff");
            staffBronze = new ItemStaff(26782, EnumNpcToolMaterial.BRONZE).setUnlocalizedName("npcBronzeStaff").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBronzeStaff");
            staffEmerald = new ItemStaff(26783, EnumNpcToolMaterial.EMERALD).setUnlocalizedName("npcEmeraldStaff").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcEmeraldStaff");
            staffElemental = new ItemElementalStaff(26784, EnumNpcToolMaterial.IRON).setUnlocalizedName("npcElementalStaff").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcElementalStaff");
            Item item36 = new ItemScythe(26785, txfz._a).setUnlocalizedName("npcWoodenScythe").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcWoodenScythe");
            item36 = new ItemScythe(26786, txfz._b).setUnlocalizedName("npcStoneScythe").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcStoneScythe");
            item36 = new ItemScythe(26787, txfz._c).setUnlocalizedName("npcIronScythe").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcIronScythe");
            item36 = new ItemScythe(26788, txfz._e).setUnlocalizedName("npcGoldenScythe").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcGoldenScythe");
            item36 = new ItemScythe(26789, txfz._d).setUnlocalizedName("npcDiamondScythe").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcDiamondScythe");
            item36 = new ItemScythe(26798, txfz3).setUnlocalizedName("npcEmeraldScythe").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcEmeraldScythe");
            item36 = new ItemScythe(26797, txfz2).setUnlocalizedName("npcBronzeScythe").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBronzeScythe");
            Item item37 = new ItemGlaive(26790, txfz._a).setUnlocalizedName("npcWoodenGlaive").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcWoodenGlaive");
            item37 = new ItemGlaive(26791, txfz._b).setUnlocalizedName("npcStoneGlaive").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcStoneGlaive");
            item37 = new ItemGlaive(26792, txfz._c).setUnlocalizedName("npcIronGlaive").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcIronGlaive");
            item37 = new ItemGlaive(26793, txfz._e).setUnlocalizedName("npcGoldenGlaive").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcGoldenGlaive");
            item37 = new ItemGlaive(26794, txfz._d).setUnlocalizedName("npcDiamondGlaive").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcDiamondGlaive");
            item37 = new ItemGlaive(26795, txfz2).setUnlocalizedName("npcBronzeGlaive").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcBronzeGlaive");
            item37 = new ItemGlaive(26796, txfz3).setUnlocalizedName("npcEmeraldGlaive").setFull3D().setMaxStackSize(1).setTextureName("customnpcs:npcEmeraldGlaive");
            Item item38 = new NpcArmor(26860, EnumArmorMaterial._b, 0, "cowleather").setUnlocalizedName("npcCowleatherHead").setMaxStackSize(1).setTextureName("customnpcs:npcCowleatherHead");
            Item item39 = new NpcArmor(26861, EnumArmorMaterial._b, 1, "cowleather").setUnlocalizedName("npcCowleatherChest").setMaxStackSize(1).setTextureName("customnpcs:npcCowleatherChest");
            item39 = new NpcArmor(26862, EnumArmorMaterial._b, 2, "cowleather").setUnlocalizedName("npcCowleatherLegs").setMaxStackSize(1).setTextureName("customnpcs:npcCowleatherLegs");
            item39 = new NpcArmor(26863, EnumArmorMaterial._b, 3, "cowleather").setUnlocalizedName("npcCowleatherBoots").setMaxStackSize(1).setTextureName("customnpcs:npcCowleatherBoots");
            item39 = new NpcArmor(26864, EnumArmorMaterial._c, 0, "nanorum").setUnlocalizedName("npcNanorumHead").setMaxStackSize(1).setTextureName("customnpcs:npcNanorumHead");
            item39 = new NpcArmor(26865, EnumArmorMaterial._c, 1, "nanorum").setUnlocalizedName("npcNanorumChest").setMaxStackSize(1).setTextureName("customnpcs:npcNanorumChest");
            item39 = new NpcArmor(26866, EnumArmorMaterial._c, 2, "nanorum").setUnlocalizedName("npcNanorumLegs").setMaxStackSize(1).setTextureName("customnpcs:npcNanorumLegs");
            item39 = new NpcArmor(26867, EnumArmorMaterial._c, 3, "nanorum").setUnlocalizedName("npcNanorumBoots").setMaxStackSize(1).setTextureName("customnpcs:npcNanorumBoots");
            item39 = new NpcArmor(26868, EnumArmorMaterial._c, 0, "tactical").setUnlocalizedName("npcTacticalHead").setMaxStackSize(1).setTextureName("customnpcs:npcTacticalHead");
            item39 = new NpcArmor(26869, EnumArmorMaterial._c, 1, "tactical").setUnlocalizedName("npcTacticalChest").setMaxStackSize(1).setTextureName("customnpcs:npcTacticalChest");
            item39 = new NpcArmor(26919, EnumArmorMaterial._c, 0, "fullcloth").setUnlocalizedName("npcFullLeatherHead").setMaxStackSize(1).setTextureName("customnpcs:npcFullLeatherHead");
            item39 = new NpcArmor(26920, EnumArmorMaterial._c, 1, "fullcloth").setUnlocalizedName("npcFullLeatherChest").setMaxStackSize(1).setTextureName("customnpcs:npcFullLeatherChest");
            item39 = new NpcArmor(26870, EnumArmorMaterial._c, 0, "fulliron").setUnlocalizedName("npcFullIronHead").setMaxStackSize(1).setTextureName("customnpcs:npcFullIronHead");
            item39 = new NpcArmor(26871, EnumArmorMaterial._c, 1, "fulliron").setUnlocalizedName("npcFullIronChest").setMaxStackSize(1).setTextureName("customnpcs:npcFullIronChest");
            item39 = new NpcArmor(26872, EnumArmorMaterial._d, 0, "fullgold").setUnlocalizedName("npcFullGoldHead").setMaxStackSize(1).setTextureName("customnpcs:npcFullGoldHead");
            item39 = new NpcArmor(26873, EnumArmorMaterial._d, 1, "fullgold").setUnlocalizedName("npcFullGoldChest").setMaxStackSize(1).setTextureName("customnpcs:npcFullGoldChest");
            item39 = new NpcArmor(26874, EnumArmorMaterial._e, 0, "fulldiamond").setUnlocalizedName("npcFullDiamondHead").setMaxStackSize(1).setTextureName("customnpcs:npcFullDiamondHead");
            item39 = new NpcArmor(26875, EnumArmorMaterial._e, 1, "fulldiamond").setUnlocalizedName("npcFullDiamondChest").setMaxStackSize(1).setTextureName("customnpcs:npcFullDiamondChest");
            item39 = new NpcArmor(26876, EnumArmorMaterial._c, 0, "fullbronze").setUnlocalizedName("npcFullBronzeHead").setMaxStackSize(1).setTextureName("customnpcs:npcFullBronzeHead");
            item39 = new NpcArmor(26877, EnumArmorMaterial._c, 1, "fullbronze").setUnlocalizedName("npcFullBronzeChest").setMaxStackSize(1).setTextureName("customnpcs:npcFullBronzeChest");
            item39 = new NpcArmor(26878, EnumArmorMaterial._c, 2, "fullbronze").setUnlocalizedName("npcFullBronzeLeggings").setMaxStackSize(1).setTextureName("customnpcs:npcFullBronzeLeggings");
            item39 = new NpcArmor(26879, EnumArmorMaterial._c, 3, "fullbronze").setUnlocalizedName("npcFullBronzeBoots").setMaxStackSize(1).setTextureName("customnpcs:npcFullBronzeBoots");
            item39 = new NpcArmor(26921, EnumArmorMaterial._e, 0, "fullemerald").setUnlocalizedName("npcFullEmeraldHead").setMaxStackSize(1).setTextureName("customnpcs:npcFullEmeraldHead");
            item39 = new NpcArmor(26922, EnumArmorMaterial._e, 1, "fullemerald").setUnlocalizedName("npcFullEmeraldChest").setMaxStackSize(1).setTextureName("customnpcs:npcFullEmeraldChest");
            item39 = new NpcArmor(26923, EnumArmorMaterial._e, 2, "fullemerald").setUnlocalizedName("npcFullEmeraldLeggings").setMaxStackSize(1).setTextureName("customnpcs:npcFullEmeraldLeggings");
            item39 = new NpcArmor(26924, EnumArmorMaterial._e, 3, "fullemerald").setUnlocalizedName("npcFullEmeraldBoots").setMaxStackSize(1).setTextureName("customnpcs:npcFullEmeraldBoots");
            item39 = new NpcArmor(26880, EnumArmorMaterial._b, 0, "fullwood").setUnlocalizedName("npcFullWoodenHead").setMaxStackSize(1).setTextureName("customnpcs:npcFullWoodenHead");
            item39 = new NpcArmor(26881, EnumArmorMaterial._b, 1, "fullwood").setUnlocalizedName("npcFullWoodenChest").setMaxStackSize(1).setTextureName("customnpcs:npcFullWoodenChest");
            item39 = new NpcArmor(26882, EnumArmorMaterial._b, 2, "fullwood").setUnlocalizedName("npcFullWoodenLeggings").setMaxStackSize(1).setTextureName("customnpcs:npcFullWoodenLeggings");
            item39 = new NpcArmor(26883, EnumArmorMaterial._b, 3, "fullwood").setUnlocalizedName("npcFullWoodenBoots").setMaxStackSize(1).setTextureName("customnpcs:npcFullWoodenBoots");
            item39 = new NpcArmor(26884, EnumArmorMaterial._b, 1, "tuxido").setUnlocalizedName("npcTuxedoChest").setMaxStackSize(1).setTextureName("customnpcs:npcTuxedoChest");
            item39 = new NpcArmor(26885, EnumArmorMaterial._b, 2, "tuxido").setUnlocalizedName("npcTuxedoPants").setMaxStackSize(1).setTextureName("customnpcs:npcTuxedoPants");
            item39 = new NpcArmor(26886, EnumArmorMaterial._b, 3, "tuxido").setUnlocalizedName("npcTuxedoBottom").setMaxStackSize(1).setTextureName("customnpcs:npcTuxedoBottom");
            item39 = new NpcArmor(26887, EnumArmorMaterial._b, 0, "wizard").setUnlocalizedName("npcWizardHead").setMaxStackSize(1).setTextureName("customnpcs:npcWizardHead");
            item39 = new NpcArmor(26888, EnumArmorMaterial._b, 1, "wizard").setUnlocalizedName("npcWizardChest").setMaxStackSize(1).setTextureName("customnpcs:npcWizardChest");
            item39 = new NpcArmor(26889, EnumArmorMaterial._b, 2, "wizard").setUnlocalizedName("npcWizardPants").setMaxStackSize(1).setTextureName("customnpcs:npcWizardPants");
            item39 = new NpcArmor(26890, EnumArmorMaterial._c, 0, "assassin").setUnlocalizedName("npcAssassinHead").setMaxStackSize(1).setTextureName("customnpcs:npcAssassinHead");
            item39 = new NpcArmor(26891, EnumArmorMaterial._c, 1, "assassin").setUnlocalizedName("npcAssassinChest").setMaxStackSize(1).setTextureName("customnpcs:npcAssassinChest");
            item39 = new NpcArmor(26892, EnumArmorMaterial._c, 2, "assassin").setUnlocalizedName("npcAssassinLeggings").setMaxStackSize(1).setTextureName("customnpcs:npcAssassinLeggings");
            item39 = new NpcArmor(26893, EnumArmorMaterial._c, 3, "assassin").setUnlocalizedName("npcAssassinBoots").setMaxStackSize(1).setTextureName("customnpcs:npcAssassinBoots");
            item39 = new NpcArmor(26894, EnumArmorMaterial._c, 0, "soldier").setUnlocalizedName("npcSoldierHead").setMaxStackSize(1).setTextureName("customnpcs:npcSoldierHead");
            item39 = new NpcArmor(26895, EnumArmorMaterial._c, 1, "soldier").setUnlocalizedName("npcSoldierChest").setMaxStackSize(1).setTextureName("customnpcs:npcSoldierChest");
            item39 = new NpcArmor(26896, EnumArmorMaterial._c, 2, "soldier").setUnlocalizedName("npcSoldierLegs").setMaxStackSize(1).setTextureName("customnpcs:npcSoldierLegs");
            item39 = new NpcArmor(26897, EnumArmorMaterial._c, 3, "soldier").setUnlocalizedName("npcSoldierBottom").setMaxStackSize(1).setTextureName("customnpcs:npcSoldierBottom");
            item39 = new NpcArmor(26898, EnumArmorMaterial._e, 0, "x407").setUnlocalizedName("npcX407Head").setMaxStackSize(1).setTextureName("customnpcs:npcX407Head");
            item39 = new NpcArmor(26899, EnumArmorMaterial._e, 1, "x407").setUnlocalizedName("npcX407Chest").setMaxStackSize(1).setTextureName("customnpcs:npcX407Chest");
            item39 = new NpcArmor(26900, EnumArmorMaterial._e, 2, "x407").setUnlocalizedName("npcX407Legs").setMaxStackSize(1).setTextureName("customnpcs:npcX407Legs");
            item39 = new NpcArmor(26901, EnumArmorMaterial._e, 3, "x407").setUnlocalizedName("npcX407Boots").setMaxStackSize(1).setTextureName("customnpcs:npcX407Boots");
            item39 = new NpcArmor(26902, EnumArmorMaterial._d, 0, "commissar").setUnlocalizedName("npcCommissarHead").setMaxStackSize(1).setTextureName("customnpcs:npcCommissarHead");
            item39 = new NpcArmor(26903, EnumArmorMaterial._d, 1, "commissar").setUnlocalizedName("npcCommissarChest").setMaxStackSize(1).setTextureName("customnpcs:npcCommissarChest");
            item39 = new NpcArmor(26904, EnumArmorMaterial._d, 2, "commissar").setUnlocalizedName("npcCommissarLegs").setMaxStackSize(1).setTextureName("customnpcs:npcCommissarLegs");
            item39 = new NpcArmor(26905, EnumArmorMaterial._d, 3, "commissar").setUnlocalizedName("npcCommissarBottom").setMaxStackSize(1).setTextureName("customnpcs:npcCommissarBottom");
            item39 = new NpcArmor(26906, EnumArmorMaterial._c, 0, "infantry").setUnlocalizedName("npcInfantryHelmet").setMaxStackSize(1).setTextureName("customnpcs:npcInfantryHelmet");
            item39 = new NpcArmor(26907, EnumArmorMaterial._e, 1, "officer").setUnlocalizedName("npcOfficerChest").setMaxStackSize(1).setTextureName("customnpcs:npcOfficerChest");
            item39 = new NpcArmor(26908, EnumArmorMaterial._e, 0, "crown1").setUnlocalizedName("npcCrown2").setMaxStackSize(1).setTextureName("customnpcs:npcCrown2");
            item39 = new NpcArmor(26909, EnumArmorMaterial._e, 0, "crown2").setUnlocalizedName("npcCrown").setMaxStackSize(1).setTextureName("customnpcs:npcCrown");
            item39 = new NpcArmor(26916, EnumArmorMaterial._c, 0, "ninja").setUnlocalizedName("npcNinjaHead").setMaxStackSize(1).setTextureName("customnpcs:npcNinjaHead");
            item39 = new NpcArmor(26917, EnumArmorMaterial._c, 1, "ninja").setUnlocalizedName("npcNinjaChest").setMaxStackSize(1).setTextureName("customnpcs:npcNinjaChest");
            item39 = new NpcArmor(26918, EnumArmorMaterial._c, 2, "ninja").setUnlocalizedName("npcNinjaPants").setMaxStackSize(1).setTextureName("customnpcs:npcNinjaPants");
            letter = new ItemNpcInterface(26950).setUnlocalizedName("npcLetter").setCreativeTab(tabMisc).setTextureName("customnpcs:npcLetter");
            Item item40 = new ItemNpcInterface(26951).setUnlocalizedName("npcPlans").setCreativeTab(tabMisc).setTextureName("customnpcs:npcPlans");
            item40 = new ItemNpcInterface(26952).setUnlocalizedName("npcSatchel").setCreativeTab(tabMisc).setTextureName("customnpcs:npcSatchel");
            item40 = new ItemNpcInterface(26953).setUnlocalizedName("npcBag").setCreativeTab(tabMisc).setTextureName("customnpcs:npcBag");
            item40 = new ItemNpcInterface(26954).setUnlocalizedName("npcCrystal").setCreativeTab(tabMisc).setTextureName("customnpcs:npcCrystal");
            item40 = new ItemNpcInterface(26955).setUnlocalizedName("npcSeveredEar").setCreativeTab(tabMisc).setTextureName("customnpcs:npcSeveredEar");
            item40 = new ItemNpcInterface(26956).setUnlocalizedName("npcPhone").setCreativeTab(tabMisc).setTextureName("customnpcs:npcPhone");
            item40 = new NpcArmor(26957, EnumArmorMaterial._c, 0, "mask").setMaxStackSize(64).setUnlocalizedName("npcBanditMask").setCreativeTab(tabArmor).setTextureName("customnpcs:npcBanditMask");
            item40 = new ItemNpcInterface(26958).setUnlocalizedName("npcBrokenArrow").setCreativeTab(tabMisc).setTextureName("customnpcs:npcBrokenArrow");
            item40 = new ItemNpcInterface(26959).setUnlocalizedName("npcEarthElement").setCreativeTab(tabMisc).setTextureName("customnpcs:npcEarthElement");
            item40 = new ItemNpcInterface(26960).setUnlocalizedName("npcWaterElement").setCreativeTab(tabMisc).setTextureName("customnpcs:npcWaterElement");
            item40 = new ItemNpcInterface(26961).setUnlocalizedName("npcFireElement").setCreativeTab(tabMisc).setTextureName("customnpcs:npcFireElement");
            item40 = new ItemNpcInterface(26962).setUnlocalizedName("npcAirElement").setCreativeTab(tabMisc).setTextureName("customnpcs:npcAirElement");
            item40 = new ItemNpcInterface(26963).setUnlocalizedName("npcCarKey").setCreativeTab(tabMisc).setTextureName("customnpcs:npcCarKey");
            item40 = new ItemNpcInterface(26964).setUnlocalizedName("npcKey").setCreativeTab(tabMisc).setTextureName("customnpcs:npcKey");
            item40 = new ItemNpcInterface(26965).setUnlocalizedName("npcKey2").setCreativeTab(tabMisc).setTextureName("customnpcs:npcKey2");
            item40 = new ItemNpcInterface(26966).setUnlocalizedName("npcPendant").setCreativeTab(tabMisc).setTextureName("customnpcs:npcPendant");
            item40 = new ItemNpcInterface(26967).setUnlocalizedName("npcBlueprint").setCreativeTab(tabMisc).setTextureName("customnpcs:npcBlueprint");
            item40 = new ItemNpcInterface(26968).setUnlocalizedName("npcRing").setCreativeTab(tabMisc).setTextureName("customnpcs:npcRing");
            item40 = new ItemNpcInterface(26969).setUnlocalizedName("npcSkull").setCreativeTab(tabMisc).setTextureName("customnpcs:npcSkull");
            item40 = new ItemNpcInterface(26970).setUnlocalizedName("npcSaphire").setCreativeTab(tabMisc).setTextureName("customnpcs:npcSaphire");
            item40 = new ItemNpcInterface(26971).setUnlocalizedName("npcRuby").setCreativeTab(tabMisc).setTextureName("customnpcs:npcRuby");
            item40 = new ItemNpcInterface(26972).setUnlocalizedName("npcAmethyst").setCreativeTab(tabMisc).setTextureName("customnpcs:npcAmethyst");
            item40 = new ItemNpcInterface(26973).setUnlocalizedName("npcBronzeIngot").setCreativeTab(tabMisc).setTextureName("customnpcs:npcBronzeIngot");
            CustomItems.tabArmor.icon = item38.itemID;
            CustomItems.tabWeapon.icon = CustomItems.shuriken.itemID;
            CustomItems.tabMisc.icon = CustomItems.coinGold.itemID;
        }
    }

    private static void available() {
        for (int i = 26700; i < 27000; ++i) {
            if (Item.itemsList[i + 256] != null) continue;
            System.out.println(i + "");
        }
    }

    static {
        tab = new CreativeTabNpcs("cnpcs");
    }
}

