/*
 * Decompiled with CFR 0.152.
 */
package cpw.mods.fml.client;

import com.google.common.base.Strings;
import cpw.mods.fml.client.FMLClientHandler;
import cpw.mods.fml.client.GuiSlotModList;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.ModContainer;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.FontRenderer;
import net.minecraft.client.gui.GuiButton;
import net.minecraft.client.gui.GuiScreen;
import net.minecraft.client.renderer.Tessellator;
import net.minecraft.client.renderer.texture.TextureManager;
import net.minecraft.util.ResourceLocation;
import org.lwjgl.opengl.GL11;

public class GuiModList
extends GuiScreen {
    private GuiScreen mainMenu;
    private GuiSlotModList modList;
    private int selected = -1;
    private ModContainer selectedMod;
    private int listWidth;
    private ArrayList<ModContainer> mods;

    public GuiModList(GuiScreen guiScreen) {
        this.mainMenu = guiScreen;
        this.mods = new ArrayList();
        FMLClientHandler.instance().addSpecialModEntries(this.mods);
        for (ModContainer modContainer : Loader.instance().getModList()) {
            if (modContainer.getMetadata() != null && modContainer.getMetadata().parentMod == null && !Strings.isNullOrEmpty(modContainer.getMetadata().parent)) {
                String string = modContainer.getMetadata().parent;
                ModContainer modContainer2 = Loader.instance().getIndexedModList().get(string);
                if (modContainer2 != null) {
                    modContainer.getMetadata().parentMod = modContainer2;
                    modContainer2.getMetadata().childMods.add(modContainer);
                    continue;
                }
            } else if (modContainer.getMetadata() != null && modContainer.getMetadata().parentMod != null) continue;
            this.mods.add(modContainer);
        }
    }

    @Override
    public void initGui() {
        for (ModContainer modContainer : this.mods) {
            this.listWidth = Math.max(this.listWidth, this.getFontRenderer()._b(modContainer.getName()) + 10);
            this.listWidth = Math.max(this.listWidth, this.getFontRenderer()._b(modContainer.getVersion()) + 10);
        }
        this.listWidth = Math.min(this.listWidth, 150);
        this.buttonList.add(new baxz(6, this.width / 2 - 75, this.height - 38, wpcz._a("gui.done")));
        this.modList = new GuiSlotModList(this, this.mods, this.listWidth);
        this.modList.registerScrollButtons(this.buttonList, 7, 8);
    }

    @Override
    protected void actionPerformed(GuiButton guiButton) {
        if (guiButton.enabled) {
            switch (guiButton.id) {
                case 6: {
                    this.mc._a(this.mainMenu);
                    return;
                }
            }
        }
        super.actionPerformed(guiButton);
    }

    public int drawLine(String string, int n, int n2) {
        int n3 = this.fontRenderer._b(string, n, n2, 14151146);
        return n2 + 10;
    }

    @Override
    public void drawScreen(int n, int n2, float f) {
        this.modList.drawScreen(n, n2, f);
        this.drawCenteredString(this.fontRenderer, "Mod List", this.width / 2, 16, 0xFFFFFF);
        int n3 = this.listWidth + 20;
        if (this.selectedMod != null) {
            GL11.glEnable(3042);
            if (!this.selectedMod.getMetadata().autogenerated) {
                int n4 = 35;
                String string = this.selectedMod.getMetadata().logoFile;
                if (!string.isEmpty()) {
                    GL11.glColor4f(1.0f, 1.0f, 1.0f, 1.0f);
                    TextureManager textureManager = this.mc._R();
                    fnrl fnrl2 = FMLClientHandler.instance().getResourcePackFor(this.selectedMod.getModId());
                    try {
                        Object object;
                        BufferedImage bufferedImage = null;
                        if (fnrl2 != null) {
                            bufferedImage = fnrl2.getPackImage();
                        } else {
                            object = this.getClass().getResourceAsStream(string);
                            if (object != null) {
                                bufferedImage = ImageIO.read((InputStream)object);
                            }
                        }
                        if (bufferedImage != null) {
                            object = textureManager._a("modlogo", new sctt(bufferedImage));
                            this.mc._h._a((ResourceLocation)object);
                            Dimension dimension = new Dimension(bufferedImage.getWidth(), bufferedImage.getHeight());
                            double d = (double)dimension.width / 200.0;
                            double d2 = (double)dimension.height / 65.0;
                            double d3 = 1.0;
                            if (d > 1.0 || d2 > 1.0) {
                                d3 = 1.0 / Math.max(d, d2);
                            }
                            dimension.width = (int)((double)dimension.width * d3);
                            dimension.height = (int)((double)dimension.height * d3);
                            int n5 = 32;
                            Tessellator tessellator = Tessellator.instance;
                            tessellator.startDrawingQuads();
                            tessellator.addVertexWithUV(n3, n5 + dimension.height, this.zLevel, 0.0, 1.0);
                            tessellator.addVertexWithUV(n3 + dimension.width, n5 + dimension.height, this.zLevel, 1.0, 1.0);
                            tessellator.addVertexWithUV(n3 + dimension.width, n5, this.zLevel, 1.0, 0.0);
                            tessellator.addVertexWithUV(n3, n5, this.zLevel, 0.0, 0.0);
                            tessellator.draw();
                            n4 += 65;
                        }
                    }
                    catch (IOException iOException) {
                        // empty catch block
                    }
                }
                this.fontRenderer._a(this.selectedMod.getMetadata().name, n3, n4, 0xFFFFFF);
                n4 += 12;
                n4 = this.drawLine(String.format("Version: %s (%s)", this.selectedMod.getDisplayVersion(), this.selectedMod.getVersion()), n3, n4);
                n4 = this.drawLine(String.format("Mod ID: '%s' Mod State: %s", new Object[]{this.selectedMod.getModId(), Loader.instance().getModState(this.selectedMod)}), n3, n4);
                if (!this.selectedMod.getMetadata().credits.isEmpty()) {
                    n4 = this.drawLine(String.format("Credits: %s", this.selectedMod.getMetadata().credits), n3, n4);
                }
                n4 = this.drawLine(String.format("Authors: %s", this.selectedMod.getMetadata().getAuthorList()), n3, n4);
                n4 = this.drawLine(String.format("URL: %s", this.selectedMod.getMetadata().url), n3, n4);
                n4 = this.drawLine(this.selectedMod.getMetadata().childMods.isEmpty() ? "No child mods for this mod" : String.format("Child mods: %s", this.selectedMod.getMetadata().getChildModList()), n3, n4);
                int n6 = this.width - n3 - 20;
                if (n6 > 20) {
                    this.getFontRenderer()._a(this.selectedMod.getMetadata().description, n3, n4 + 10, n6, 0xDDDDDD);
                }
            } else {
                n3 = (this.listWidth + this.width) / 2;
                this.drawCenteredString(this.fontRenderer, this.selectedMod.getName(), n3, 35, 0xFFFFFF);
                this.drawCenteredString(this.fontRenderer, String.format("Version: %s", this.selectedMod.getVersion()), n3, 45, 0xFFFFFF);
                this.drawCenteredString(this.fontRenderer, String.format("Mod State: %s", new Object[]{Loader.instance().getModState(this.selectedMod)}), n3, 55, 0xFFFFFF);
                this.drawCenteredString(this.fontRenderer, "No mod information found", n3, 65, 0xDDDDDD);
                this.drawCenteredString(this.fontRenderer, "Ask your mod author to provide a mod mcmod.info file", n3, 75, 0xDDDDDD);
            }
            GL11.glDisable(3042);
        }
        super.drawScreen(n, n2, f);
    }

    Minecraft getMinecraftInstance() {
        return this.mc;
    }

    FontRenderer getFontRenderer() {
        return this.fontRenderer;
    }

    public void selectModIndex(int n) {
        this.selected = n;
        this.selectedMod = n >= 0 && n <= this.mods.size() ? this.mods.get(this.selected) : null;
    }

    public boolean modIndexSelected(int n) {
        return n == this.selected;
    }
}

