/*
 * Decompiled with CFR 0.152.
 */
package com.mcf.davidee.guilib;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import java.util.Arrays;

@Mod(modid="guilib", name="GUI Library", version="1.0.6.1")
public class GuiLibrary {
    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent fMLPreInitializationEvent) {
        ModMetadata modMetadata = fMLPreInitializationEvent.getModMetadata();
        modMetadata.authorList = Arrays.asList("Davidee");
        modMetadata.autogenerated = false;
        modMetadata.credits = "Thanks to Mojang, Forge, and all your support.";
        modMetadata.description = "A small library for creating minecraft GUIs.";
        modMetadata.url = "http://www.minecraftforum.net/topic/1909236-/";
    }
}

