/*
 * Decompiled with CFR 0.152.
 */
package cpw.mods.fml.common;

import argo.jdom.JdomParser;
import argo.jdom.JsonNode;
import argo.jdom.JsonRootNode;
import argo.saj.InvalidSyntaxException;
import com.google.common.base.Throwables;
import com.google.common.collect.Maps;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.ModMetadata;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.Map;
import java.util.logging.Level;

public class MetadataCollection {
    private static JdomParser parser = new JdomParser();
    private Map<String, ModMetadata> metadatas = Maps.newHashMap();
    private int metadataVersion = 1;

    public static MetadataCollection from(InputStream inputStream, String string) {
        if (inputStream == null) {
            return new MetadataCollection();
        }
        InputStreamReader inputStreamReader = new InputStreamReader(inputStream);
        try {
            JsonRootNode jsonRootNode = parser.parse(inputStreamReader);
            if (jsonRootNode.hasElements()) {
                return MetadataCollection.parse10ModInfo(jsonRootNode);
            }
            return MetadataCollection.parseModInfo(jsonRootNode);
        }
        catch (InvalidSyntaxException invalidSyntaxException) {
            FMLLog.log(Level.SEVERE, invalidSyntaxException, "The mcmod.info file in %s cannot be parsed as valid JSON. It will be ignored", string);
            return new MetadataCollection();
        }
        catch (Exception exception) {
            throw Throwables.propagate(exception);
        }
    }

    private static MetadataCollection parseModInfo(JsonRootNode jsonRootNode) {
        MetadataCollection metadataCollection = new MetadataCollection();
        metadataCollection.metadataVersion = Integer.parseInt(jsonRootNode.getNumberValue("modinfoversion"));
        metadataCollection.parseModMetadataList(jsonRootNode.getNode("modlist"));
        return metadataCollection;
    }

    private static MetadataCollection parse10ModInfo(JsonRootNode jsonRootNode) {
        MetadataCollection metadataCollection = new MetadataCollection();
        metadataCollection.parseModMetadataList(jsonRootNode);
        return metadataCollection;
    }

    private void parseModMetadataList(JsonNode jsonNode) {
        for (JsonNode jsonNode2 : jsonNode.getElements()) {
            ModMetadata modMetadata = new ModMetadata(jsonNode2);
            this.metadatas.put(modMetadata.modId, modMetadata);
        }
    }

    public ModMetadata getMetadataForId(String string, Map<String, Object> map) {
        if (!this.metadatas.containsKey(string)) {
            ModMetadata modMetadata = new ModMetadata();
            modMetadata.modId = string;
            modMetadata.name = (String)map.get("name");
            modMetadata.version = (String)map.get("version");
            modMetadata.autogenerated = true;
            this.metadatas.put(string, modMetadata);
        }
        return this.metadatas.get(string);
    }
}

